### ISSUE TITLE
An exception occurred while dispatching the request to the skill

### ISSUE THREAD

**Issue by TonySoftWare** [timheuer/alexa-skills-dotnet#127]
The error occurs when the slot is not inserted. For example,  
"**Tell me a proverb** " is corrected executed,
but  "**Tell me a** " produces the error.
Using the Mock Tool provided with Visual Studio, the Skill handles the error due to the empty slot,
but uploading it to AWS gets this error
"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.5b1a4dbf-a6dd-473e-a460-bc84b106a20a",
		"timestamp": "2019-01-27T17:32:20Z",
		"locale": "it-IT",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
Do you have an idea?

**Comment by stoiveyp** [comment]
Is there a request immediately before that one? This is normally sent because the previous request threw an exception or an invalid response object and so Alexa had to terminate the session.

Also, am I right in thinking the slot is currently optional? If you change it in the intent setup to make it required then "Tell me a" won't be considered a valid utterance, the more you can make Alexa do the work the better.

**Comment by Smartronsc** [comment]
I am interested in this error because I get this error in the canned "High Low Game'. The code can't be wrong because it is an Amazon Demo. Now I have read it can fail because it has intents for a Show device that the alexa developer console shows it does not support and various other reasons. The question is how to effectively debug  a n y t h i n g in alexa? I tried Hello World and it seem promising until it got to "Oops, I didn't work" I have looked at the cli and it seems to have it own complications. I did get cli to work and it showed me the exact error I saw originally, nothing more. Now that I am here I think I will try alexa-skills-dotnet (If it is Java), perhaps it will work.

**Comment by Smartronsc** [comment]
Ha, you were not kidding about the nothing but Net part! Oh well, off I go, High Ho High Ho.

**Comment by timheuer** [comment]
@Smartronsc I've found in my experience using logging effectively is how I've 'debugged' an actual live Alexa situation outside of tests and just ensuring the expected send/receive is validated in my serverless function.  But when deployed to alexa, logging is where I rely.

**Comment by GermanoFLeite** [comment]
Sua solicitação pode ter ultrapassado o tempo limite de 8000ms
