### ISSUE TITLE
using Alexa Skills SDK .NET for Alexa Smart Home API

### ISSUE THREAD

**Issue by WenWu5** [timheuer/alexa-skills-dotnet#200]
Hi,

I am looking for a helper library for Alexa Smart Home Skill API. Can you confirm Alexa Skills SDK .NET will not work for this? If so, do you know of any helper libraries for Alexa Smart Home API?

Thanks

**Comment by sberube** [comment]
Any news about this issue? @WenWu5 did you found something? Thanks!

**Comment by abc123xxx** [comment]
Any news about this issue?

**Comment by markschroeder77** [comment]
I'm also curious about this

**Comment by stoiveyp** [comment]
I guess the question that needs to be answered is where in the smart home journey are you hoping to find support?

If it's the custom skill code, where you need to send Smart Home directives as part of the response. Then I think this is  achievable and would probably best fit as an extension to Alexa.NET so that those requiring that support could opt in with a second NuGet package. It's a pattern we've used in other areas such as the graphics for APL.

However, if it's more smart home at a device/alexa interaction level - where you're looking for help in the actual device discovery and connection space - then this library wouldn't be fit for purpose, as that's a lower level then this API operates.

We really want to help if we can, and it would be great to hear your feedback on where you want a package like ours to help so we can see if we fit your needs.
