### ISSUE TITLE
Echo Show

### ISSUE THREAD

**Issue by psantiago1969** [timheuer/alexa-skills-dotnet#55]
Any samples for using this for Body and List Templates?
Showing Action on Body Template and retrieving the Display.ElementSelected?

Thanks!

**Comment by stoiveyp** [comment]
Hi @psantiago1969 

So for the Display.ElementSelected event it's a new request type, so you can add it to the logic in your skill that determines what action to take. Something like this should work:

```csharp            
switch (skillRequest.Request)
{
    case DisplayElementSelectedRequest element:
    var token = element.Token;
    //TODO: Perform logic here
    break;
}
```
For body and list templates you use the new DisplayRenderTemplateDirective class, add your template to that, and attach that to your response before returning a value from your skill. Something like the following

```csharp
            var template = new BodyTemplate1
            {
                Title = "Test Title",
                Token = "BodyTemplate",
                Content = new TemplateContent
                {
                    Primary = new TemplateText {Text = "This is primary text"},
                    Secondary = new TemplateText {Text = "This is secondary text"}
                }
            };

            var response = ResponseBuilder.Tell("This is the speech Alexa will use");
            response.Response.Directives.Add(new DisplayRenderTemplateDirective{Template=template});
```

For a more complete set of template examples, you might want to check out the repository [Display Tests](timheuer/alexa-skills-dotnet/blob/master/Alexa.NET.Tests/RenderTemplateTests.cs)

Unfortunately I don't have a full working sample - simply because I've yet to get hold of a device that honours the Display Directive, but the library adheres to the document definition supplied by Amazon.

Please, if you have any other questions please don't hesitate to ask.

**Comment by psantiago1969** [comment]
Thank you so much!  I really appreciate it!  Nice to see a robust library being updated!
Cheers!

**Comment by Zoba273** [comment]
you should be able to get a photo running (the template used by @stoiveyp shows 3 different texts) if you use template7 instead.
i got the token via "var token = input.Context.System.ApiAccessToken;"
`var imageSource = new List<ImageSource>();
                                var image = new ImageSource
                                {
                                    Url = nasaPic.Url.ToString()
                                };
                                imageSource.Add(image);

                                var templateImage = new TemplateImage
                                {
                                    Sources = imageSource,
                                    ContentDescription = nasaPic.Explanation
                                };
                                var template = new BodyTemplate7
                                {
                                    Title = nasaPic.Title,
                                    Token = token,
                                    Image = templateImage
                                };`
